routes/web.php
<?php

use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Auth\RestorePasswordController;
use App\Http\Controllers\Cabinet\CabinetController;
use App\Http\Controllers\Cabinet\CargoController;
use App\Http\Controllers\Cabinet\GeoLocationsController;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Page\PageController;
use App\Http\Controllers\Pages\AboutController;
use App\Http\Controllers\Pages\ContactsController;
use App\Http\Controllers\Pages\DocumentsController;
use App\Http\Controllers\Pages\DonorsController;
use App\Http\Controllers\Pages\FeedbackController;
use App\Http\Controllers\Pages\InstructionController;
use App\Http\Controllers\Pages\MarketplaceController;
use App\Http\Controllers\Pages\RecipientsController;
use App\Http\Controllers\Pages\WhatIsDoneController;
use App\Models\User;
use App\Notifications\CustomAidRequestNotification;
use App\Notifications\EveryDayNewAidКequestNotification;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Route;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::get('/', function () {
    return redirect(app()->getLocale());
});

Route::group(['prefix' => LaravelLocalization::setLocale()], function()
{
    Route::view('render-component', 'livewire.component')->name('render-component');

    //  Cabinet
    Route::group(['prefix' => 'cabinet', 'as' => 'cabinet.', 'middleware' => 'auth.check'], function() {
        Route::get('/', [CabinetController::class, 'index'])
            ->name('home');
        Route::get('/regenerate-files/asyfdvgVGShgVSHGVDHSTGVhgVSHFcVHSGVHGSVhjBSJGvHGSjb', [CabinetController::class, 'regenerateFiles'])
            ->name('regenerateFiles');
        /*Route::get('/user/{user?}', [CabinetController::class, 'index'])
            ->name('home.user');*/
        Route::get('/new-shipment', [CargoController::class, 'newShipment'])
            ->name('new-shipment');
        Route::get('/new-shipment/received', [CargoController::class, 'newShipmentReceived'])
            ->name('new-shipment-received');

        Route::get('/sign-document/{transferDocument}', [CargoController::class, 'signDocument'])
            ->name('sign-document');

        Route::get('/accept-cargo/{transfer}', [CargoController::class, 'accept'])
            ->name('accept-cargo');
        Route::get('/approve/{transfer}', [CargoController::class, 'approve'])
            ->name('approve');
        Route::get('/locations/{transfer}', [GeoLocationsController::class, 'index'])
            ->name('locations.cargo');
        Route::get('/locations/{transfer}/json', [GeoLocationsController::class, 'indexJson'])
            ->name('locations.cargo.json');
        Route::get('/cargo-document', [CargoController::class, 'document'])
            ->name('cargo-document');
        Route::get('/{transfer}/cargo-qr-code', [CargoController::class, 'printQrCode'])
            ->name('cargo-qr-code');
        Route::get('/{transfer}/document-test', [CargoController::class, 'testDocument'])
            ->name('cargo-doc-test');
        Route::get('/donate-products/{transfer?}', [CargoController::class, 'donate'])
            ->name('donate-product');
        Route::get('/recipient/donate-products', [CargoController::class, 'donateRecipient'])
            ->name('donate-product-recipient');
        Route::get('/people/donate-products', [CargoController::class, 'donatePeople'])
            ->name('donate-product-people');
        Route::get('/download-act/{transfer}', [CargoController::class, 'downloadAct'])
            ->name('download-act');
        Route::get('/download-act-accept/{transfer}', [CargoController::class, 'downloadActAccept'])
            ->name('download-act-accept');
        Route::get('/settings', [CabinetController::class, 'settings'])
            ->name('settings');
        Route::get('/users', [CabinetController::class, 'users'])
            ->name('users');
        Route::get('/warehouse', [CabinetController::class, 'warehouse'])
            ->name('warehouse');

        Route::get('/aid-requests', [\App\Http\Controllers\Cabinet\AidRequest\AidRequestController::class, 'index'])
            ->name('aid-requests.index');
        Route::get('/aid-request/create', [\App\Http\Controllers\Cabinet\AidRequest\AidRequestController::class, 'create'])
            ->name('aid-requests.create');
        Route::get('/aid-request/{id}/update', [\App\Http\Controllers\Cabinet\AidRequest\AidRequestController::class, 'update'])
            ->name('aid-requests.update');

    });

    Route::get('/cabinet/cargo/{transfer}', [CargoController::class, 'cargo'])
        ->name('cabinet.cargo');
    Route::post('/cargo/{transfer}/save-location', [CargoController::class, 'cargoLocation'])
        ->name('cabinet.cargo.save-location');


    Route::get('/cargo/{cargo}/keeex-url', [CargoController::class, 'redirectKeeexUrl'])
        ->name('redirectKeeexUrl');

    Route::get('/verify-email/{token}', [CabinetController::class, 'verify'])
        ->name('verify-email');

    // Auth
    Route::get('/login/is-admin/{id}', \App\Http\Controllers\Auth\LoginController::class)
        ->middleware(['admin', 'platform'])
        ->name('login.admin');
    Route::get('/logout', LogoutController::class)
        ->name('logout');
    Route::get('/restore-password/{token}', RestorePasswordController::class)
        ->name('restore-password');

    // Home
    Route::get('/', HomeController::class)->name('home');

    // Pages
    Route::get('/country-photos/{country}', [CargoController::class, 'countryPhotos'])
        ->name('country-photos');

    Route::get('about-us', [AboutController::class, 'index'])->name('page.about');
    Route::get('marketplace', [MarketplaceController::class, 'index'])->name('page.marketplace');
    Route::get('documents', [DocumentsController::class, 'index'])->name('page.documents');
    Route::get('documents/{pdf}', [DocumentsController::class, 'document'])->name('page.documents.pdf');
    //Route::get('contacts', [ContactsController::class, 'index'])->name('page.contacts');
    Route::get('feedback', [FeedbackController::class, 'index'])->name('page.feedback');
    Route::get('what-is-done', [WhatIsDoneController::class, 'index'])->name('page.whatIsDone');
    Route::get('5tguI7ftfvCjFGCmgvn', [CabinetController::class, 'reloadData']);
    Route::get('what-is-done/{slug}', [WhatIsDoneController::class, 'itemView'])->name('page.whatIsDone.page');
    Route::get('donors', [DonorsController::class, 'index'])->name('page.donors');
    Route::get('donors/{organisation}', [DonorsController::class, 'show'])->name('page.donors.show');
    Route::get('recipients', [RecipientsController::class, 'index'])->name('page.recipients');
    Route::get('recipients/{organisation}', [RecipientsController::class,'show'])->name('page.recipients.show');
    Route::get('instruction', [InstructionController::class, 'index'])->name('instruction');
    //Route::get('{page}', PageController::class)->name('page');

});

resources/views/widgets/authorization.blade.php
<div class="authorization">
    <div class="_flex _justify-between">
        @svg('content', 'user', [16, 19], 'authorization__icon _xs:show _mr-xs')

        @auth
            <a href="{{ route('cabinet.home') }}" class="authorization__link
                                            @if(stripos(url()->current(), 'cabinet')) is-active @endif">
                {{__('auth.Cabinet')}}
            </a>
            <span class="authorization__slash">/</span>
            <a href="{{ route('logout') }}" class="authorization__link">{{__('auth.Logout')}}</a>
        @else
            <span
                x-data="Alpine.plugins.openModal('auth.login')"
                @click="open"
                class="authorization__link">{{__('auth.Login')}}</span>
            <span class="authorization__slash">/</span>
            <span
                x-data="Alpine.plugins.openModal('auth.registration')"
                @click="open"
                class="authorization__link">{{__('auth.Register')}}</span>
        @endauth
    </div>
</div>

resources/views/widgets/breadcrumbs.blade.php
<div class="breadcrumbs">
    <div class="breadcrumbs__list">
        @foreach(Seo::breadcrumbs()->elements() as $element)
            @if($element->getUrl() != '#')
            <a href="{{ $element->getUrl() }}" class="breadcrumbs__link">
                {{ $element->getTitle() }}
            </a>
            <span> / </span>
            @else
                <span class="breadcrumbs__link">
                    {{ $element->getTitle() }}
                </span>
            @endif
        @endforeach
    </div>
</div>

resources/views/widgets/color-info.blade.php
<div>
    <div class="color-info _flex-wrap _mb-df">
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-new', 14)
            {{__('dashboard.New undivided assistance')}}
        </div>
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-all', 14)
            {{__('dashboard.All done')}}
        </div>
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-process', 14)
            {{__('dashboard.In process')}}
        </div>
    </div>
    <div class="color-info _flex-wrap _mb-df">
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-approval', 12)
            {{ __('cargo.statuses.List approval') }}
        </div>
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-no-confirmed', 12)
            {{ __('cargo.statuses.List not confirmed') }}
        </div>
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-confirmed', 12)
            {{ __('cargo.statuses.List confirmed') }}
        </div>
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-delivery-no-confirmed', 12)
            {{ __('cargo.statuses.Delivery not confirmed') }}
        </div>
        <div class="color-info__icon _mr-df _mb-sm">
            @svg('dashboard', 'color-delivery-confirmed', 12)
            {{ __('cargo.statuses.Delivery confirmed') }}
        </div>
    </div>
</div>

resources/views/widgets/faq.blade.php
@if($list->count())
<div class="_flex _justify-between _items-center _mb-md _md:mb-xl" id="faq">
    <div>
        <div class="title title--size-h1 _mb-md _df:mb-lg">
            FAQ
        </div>

        <div class="title title--size-h3">
            {{ __('faq.We will answer all questions') }}
        </div>
    </div>
</div>

    @foreach($list as $faq)
        <div class="faq _mb-md _md:mb-df">
            <div class="faq__question js-import" data-accordion="faq">
                <div class="_flex">
                    <div class="_mr-xs">{{ $loop->iteration }}.</div>
                    {!! $faq->question !!}
                </div>
                <svg class="_md:show" width="23" height="13" viewBox="0 0 23 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <line y1="-1" x2="15" y2="-1" transform="matrix(-0.707107 0.707107 0.707107 0.707107 22.4556 2)" stroke="white" stroke-width="2"/>
                    <line x1="1.55574" y1="1.29387" x2="12.1623" y2="11.9005" stroke="white" stroke-width="2"/>
                </svg>
                <svg class="_md:hide" width="13" height="7" viewBox="0 0 13 7" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M1.242 1.64359C0.949102 1.3507 0.949103 0.875823 1.242 0.58293C1.53489 0.290036 2.00976 0.290036 2.30266 0.58293L7.07514 5.35541C7.36803 5.64831 7.36803 6.12318 7.07514 6.41607C6.78225 6.70897 6.30737 6.70897 6.01448 6.41607L1.242 1.64359Z" fill="white"/>
                    <path d="M11.9689 1.64359C12.2618 1.3507 12.2618 0.875823 11.9689 0.58293C11.676 0.290036 11.2012 0.290036 10.9083 0.58293L6.1358 5.35541C5.84291 5.64831 5.84291 6.12318 6.1358 6.41607C6.42869 6.70897 6.90357 6.70897 7.19646 6.41607L11.9689 1.64359Z" fill="white"/>
                </svg>

            </div>
            <div class="faq__answer">
                {!! $faq->answer !!}
            </div>
        </div>
    @endforeach
@endif

resources/views/widgets/lang_switcher.blade.php
<div class="language-switcher _justify-around _xs:justify-start">
    @foreach($locales as $locale)
            @if($locale['active'])
                <span class="language-switcher__item">
                     {{ $locale['name'] }}
                </span>
            @else
                <a class="language-switcher__item" rel="alternate" hreflang="{{ $locale['link'] }}" href="{{ $locale['link'] }}">
                    {{ $locale['name'] }}
                </a>
            @endif
    @endforeach
</div>

resources/views/widgets/marketplace-home.blade.php
<div class="section section--marketplace">
    <div class="_flex _flex-column">
        @if($listOffer->isNotEmpty())

            <div class="marketplace__line _pb-xs">
                <div class="container">
                    <div class="_flex _items-center">
                        <div class="marketplace__title">
                            @svg('marketplace', 'offer', [28, 25])
                            {{ __('aid-request.marketplace.We offer') }}
                        </div>

                        <div class="marketplace__run-line js-import" data-marquee="15000">
                            <a href="{{ route('page.marketplace') }}">
                                @foreach($listOffer as $item)
                                    <span>{{ $item->description }}</span>
                                @endforeach
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        @endif

        @if($listNeed->isNotEmpty())
            <div class="marketplace__line _pt-xs">
                <div class="container">
                    <div class="_flex _items-center">
                        <div class="marketplace__title">
                            @svg('marketplace', 'required', [21, 27])
                            {{ __('aid-request.marketplace.Required') }}
                        </div>

                        <div class="marketplace__run-line js-import" data-marquee="18000">
                            <a href="{{ route('page.marketplace') }}">
                                @foreach($listNeed as $item)
                                    <span>{{ $item->description }}</span>
                                @endforeach
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        @endif
    </div>
</div>

resources/views/widgets/menu.blade.php
<div class="menu _m-auto _pl-xs _pr-xs">
    <div class="_flex _justify-between _spacer _spacer--xxl _df:spacer--md _lg:spacer--xl _xl:spacer--xl">
        <div class="menu__item">
            <a href="{{ route('page.about') }}" class="menu__link @if(stripos(url()->current(), route('page.about')) !== false) is-active @endif">
                {{__('default.About us')}}</a>
        </div>
       {{-- <div class="menu__item">
            <a href="{{ route('page.whatIsDone') }}" class="menu__link @if(stripos(url()->current(), route('page.whatIsDone')) !== false) is-active @endif">
                {{__('default.What is done')}}
            </a>
        </div>--}}
        <div class="menu__item">
            <a href="{{ route('page.donors') }}" class="menu__link @if(stripos(url()->current(), route('page.donors')) !== false) is-active @endif">
                {{__('default.Donors')}}
            </a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.recipients') }}" class="menu__link @if(stripos(url()->current(), route('page.recipients')) !== false) is-active @endif">
                {{__('default.Recipients')}}
            </a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.marketplace') }}" class="menu__link  @if(stripos(url()->current(), route('page.marketplace')) !== false) is-active @endif"> {{__('default.Marketplace')}}</a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.feedback') }}" class="menu__link  @if(stripos(url()->current(), route('page.feedback')) !== false) is-active @endif"> {{__('default.Feedback')}}</a>
        </div>
        <div class="menu__item">
            <a href="{{ route('home') }}#faq" class="menu__link anchor" data-anchor="faq">FAQ</a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.documents') }}" class="menu__link  @if(stripos(url()->current(), route('page.documents')) !== false) is-active @endif"> {{__('default.Documents')}}</a>
        </div>
    </div>
</div>

resources/views/widgets/menu_mobile.blade.php
<div class="menu__hamburger _lg:hide _ml-md js-import" data-hamburger>
    <svg class="close" width="22" height="17" viewBox="0 0 22 17" fill="none" xmlns="http://www.w3.org/2000/svg">
        <rect y="14" width="22" height="3" rx="1.5" fill=""/>
        <rect y="7" width="22" height="3" rx="1.5" fill=""/>
        <path d="M8 1.5C8 0.671573 8.67157 0 9.5 0H20.5C21.3284 0 22 0.671573 22 1.5C22 2.32843 21.3284 3 20.5 3H9.5C8.67157 3 8 2.32843 8 1.5Z" fill=""/>
    </svg>

    <svg class="open" width="21" height="22" viewBox="0 0 21 22" fill="none" xmlns="http://www.w3.org/2000/svg">
        <path class="cl1" d="M0.954055 20.545C0.563531 20.1545 0.563531 19.5213 0.954055 19.1308L18.6317 1.45311C19.0222 1.06259 19.6554 1.06259 20.0459 1.45311C20.4365 1.84364 20.4365 2.4768 20.0459 2.86733L2.36827 20.545C1.97774 20.9355 1.34458 20.9355 0.954055 20.545Z" fill=""/>
        <path class="cl1" d="M19.799 20.5445C20.1895 20.154 20.1895 19.5208 19.799 19.1303L2.12133 1.45263C1.7308 1.0621 1.09764 1.0621 0.707114 1.45263C0.31659 1.84315 0.31659 2.47632 0.707114 2.86684L18.3848 20.5445C18.7753 20.935 19.4085 20.935 19.799 20.5445Z" fill=""/>
    </svg>
</div>

<div class="menu menu--mobile">
    <div class="menu__wrapper">
        <div class="menu__item menu__item--fixed _xs:hide _pt-md _pb-md">
            @widget('langSwitcher')
        </div>
        <div class="menu__item">
            <a href="{{ route('page.about') }}" class="menu__link @if(stripos(url()->current(), route('page.about')) !== false) is-active @endif">
                {{__('default.About us')}}</a>
        </div>
        {{-- <div class="menu__item">
             <a href="{{ route('page.whatIsDone') }}" class="menu__link @if(stripos(url()->current(), route('page.whatIsDone')) !== false) is-active @endif">
                 {{__('default.What is done')}}
             </a>
         </div>--}}
        <div class="menu__item">
            <a href="{{ route('page.donors') }}" class="menu__link @if(stripos(url()->current(), route('page.donors')) !== false) is-active @endif">
                {{__('default.Donors')}}
            </a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.recipients') }}" class="menu__link @if(stripos(url()->current(), route('page.recipients')) !== false) is-active @endif">
                {{__('default.Recipients')}}
            </a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.marketplace') }}" class="menu__link  @if(stripos(url()->current(), route('page.marketplace')) !== false) is-active @endif"> {{__('default.Marketplace')}}</a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.feedback') }}" class="menu__link  @if(stripos(url()->current(), route('page.feedback')) !== false) is-active @endif"> {{__('default.Feedback')}}</a>
        </div>
        <div class="menu__item">
            <a href="{{ route('home') }}#faq" class="menu__link anchor" data-anchor="faq">FAQ</a>
        </div>
        <div class="menu__item">
            <a href="{{ route('page.documents') }}" class="menu__link  @if(stripos(url()->current(), route('page.documents')) !== false) is-active @endif"> {{__('default.Documents')}}</a>
        </div>
    </div>
</div>

resources/views/widgets/notifications.blade.php
@php
    use Illuminate\Support\Arr;
    use App\Notifications\SignDocumentNotification;

@endphp
<div class="ring">
    @if($list->count() > 0)
        <span class="ring__count" style="--fa-animation-iteration-count: 2">{{ $list->count() }}</span>
    @endif
    <i class="fa-solid fa-bell fa-shake fa-xl" style="--fa-animation-iteration-count: 2"></i>
    <div class="ring__block">
        @foreach($list as $notification)
            @if($notification->type == \App\Notifications\SignDocumentNotification::class )
                <a href="{{ \Illuminate\Support\Arr::get($notification->data, 'route') ? route(\Illuminate\Support\Arr::get($notification->data, 'route'), \Illuminate\Support\Arr::get($notification->data, 'route_params') + ['notification' =>$notification->id]) : '#' }}"
                   class="ring__item">
                    {{ __(\Illuminate\Support\Arr::get($notification->data, 'title')) }}
                    <br>
                    {{ Arr::get($notification->data, 'description') }}
                    <i class="fa-sharp fa-solid fa-circle-check _ml-xs"></i>
                </a>
            @else
                <a href="{{ \Illuminate\Support\Arr::get($notification->data, 'route') ? route(\Illuminate\Support\Arr::get($notification->data, 'route'), \Illuminate\Support\Arr::get($notification->data, 'route_params')) : '#' }}"
                   class="ring__item">
                    {{ __(Arr::get($notification->data, 'title')) }}
                    <i class="fa-sharp fa-solid fa-circle-check _ml-xs"></i>
                </a>
            @endif
        @endforeach
        @if($list->count() == 0)
            <span class="ring__item">
                    {{ __('notifications.There are no messages!') }}
                </span>
        @endif
    </div>
</div>

resources/views/widgets/pagination.blade.php
@if ($paginator->hasPages())
    <div class="_flex _justify-between _items-center _mt-md">
        <div class="pagination">
            <div class="_grid _spacer _spacer--sm">
                @if ($paginator->onFirstPage())
                    <div class="_cell">
                        <div class="pagination__item pagination__item--withoutBorder">
                            < <span>{{__('default.Previous')}} </span>
                        </div>
                    </div>
                @else
                    <div class="_cell">
                        <div class="pagination__item pagination__item--withoutBorder">
                            <a href="{{$paginator->previousPageUrl()}}">< <span>{{__('default.Previous')}}</span> </a>
                        </div>
                    </div>
                @endif
                @if($paginator->currentPage() != 1)
                    <div class="_cell">
                        <div class="pagination__item">
                            <a href="{{routeLocale(\Illuminate\Support\Facades\Route::current()->getName())}}">1 ...</a>
                        </div>
                    </div>
                @endif

                <div class="_cell">
                    <div class="pagination__item is-active">
                        <span>{{ $paginator->currentPage() }}</span>
                    </div>
                </div>
                @if($paginator->currentPage() + 1 <= $paginator->lastPage())
                    <div class="_cell">
                        <div class="pagination__item">
                            <a href="{{routeLocale(\Illuminate\Support\Facades\Route::current()->getName(), ['page' => $paginator->currentPage() + 1])}}"> {{$paginator->currentPage() + 1}} </a>
                        </div>
                    </div>
                @endif
                @if($paginator->currentPage() + 2 <= $paginator->lastPage())
                    <div class="_cell">
                        <div class="pagination__item">
                            <a href="{{routeLocale(\Illuminate\Support\Facades\Route::current()->getName(), ['page' => $paginator->currentPage() + 2])}}"> {{$paginator->currentPage() + 2}} </a>
                        </div>
                    </div>
                @endif
                @if($paginator->currentPage() != $paginator->lastPage())
                    <div class="_cell">
                        <div class="pagination__item">
                            <a href="{{routeLocale(\Illuminate\Support\Facades\Route::current()->getName(), ['page' => $paginator->lastPage()])}}">... {{$paginator->lastPage()}}</a>
                        </div>
                    </div>
                @endif
                @if ($paginator->hasMorePages())
                    <div class="_cell">
                        <div class="pagination__item pagination__item--withoutBorder">
                            <a href="{{$paginator->nextPageUrl()}}"><span>{{__('default.Next')}}</span> ></a>
                        </div>
                    </div>
                @else
                    <div class="_cell">
                        <div class="pagination__item pagination__item--withoutBorder">
                            <span>{{__('default.Next')}}</span> >
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endif

resources/views/widgets/registration-button.blade.php
<div class="_flex _flex-column _sm:flex-row _items-start">
    <div  x-data="Alpine.plugins.openModal('auth.registration', {{json_encode(['type' => 'donor'])}})"
          @click="open"
          @mouseenter="open"
          class="button button--normal button--main _mr-df _mb-md _sm:mb-none">
        <span class="_flex _items-end">
            <span>Become a donor</span>
            <i class="_ml-sm _mt-xxs fa-solid fa-arrow-right"></i>
        </span>
    </div>
    <div
        x-data="Alpine.plugins.openModal('auth.registration', {{json_encode(['type' => 'recipient'])}})"
        @click="open"
        @mouseenter="open"
        class="button button--normal button--main">
        <span class="_flex _items-end">
            <span>Ask for help</span>
            <i class="_ml-sm _mt-xxs fa-solid fa-arrow-right"></i>
        </span>
    </div>
</div>

resources/views/widgets/slider.blade.php
<div class="_flex _justify-between _items-center _mb-md _md:mb-xl">
    <div>
        <div class="title title--size-h1 _mb-md _df:mb-lg">
            What is done
        </div>

        <div class="title title--size-h3">
            The latest updates
        </div>
    </div>
</div>

<div class="_mb-xl">
    <div class="_flex _flex-column-reverse _sm:flex-row">
        <div class="news-text">
            <div class="news-card__text-title"></div>
        </div>
        <div class="news-slider _overflow">
            <div class="news-slider__slider swiper-container js-import"
                 data-swiper-slider='{"containerClass":"news-slider__slider","type":"NewsSlider","navigation":{"type":"default-outside","outside":true}}'>
                <div class="swiper-wrapper">
                    @foreach($transfers as $transfer)
                        @if($transfer->getImages()->count())
                            <div class="news-card swiper-slide">
                                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
                                    data-src="{{$transfer->getImages()->first()->getUrl()}}" loading="lazy" class="swiper-lazy news-card__image">
                                <div class="news-card__text _hide">
                                    <div class="news-card__text-title">
                                        From {{$transfer->sender->city}}
                                        <span>{{$transfer->created_at->toDateString()}}</span>
                                    </div>
                                    {{--                        text--}}
                                </div>
                            </div>
                        @else
                            <div class="news-card swipper-slide">
                                <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
                                    data-src="{{asset('/images/noimage.jpg')}}" loading="lazy" class="swiper-lazy news-card__image">
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>
        </div>
    </div>

    <div class="slider-navigation slider-navigation--under-slider">
        <div class="slider-navigation__button slider-navigation__button--prev swiper-button-prev swiper-button-disabled">
            @svg('slider', 'prev', [40, 41])
        </div>
        <div class="slider-navigation__button slider-navigation__button--next swiper-button-next">
            @svg('slider', 'next', [40, 41])
        </div>
    </div>
</div>

resources/views/widgets/social-icons.blade.php
<div class="soc-widget is-hide">
    <div class="btn_wrap">
        <span>Зв'язатися з нами</span>
        <div class="container">
            <a href="https://t.me/aidmonitor" target="_blank">
                <i class="fa-brands fa-telegram"></i>
            </a>
            {{--                <a href="">--}}
            {{--                    <i class="fa-solid fa-envelope"></i>--}}
            {{--                </a>--}}
        </div>
    </div>
</div>